version: "3.9"

services:
  foxglove:
    container_name: "${CONTAINER_NAME:-foxglove-${USER}}"
    image: registry.robotics-lab.ru/foxglove:0.3.0
    tty: true
    build:
      context: .
      tags:
          - "registry.robotics-lab.ru/foxglove:latest"
          - "registry.robotics-lab.ru/foxglove:0.3.0"
      x-bake:
        platforms:
          - linux/arm64
          - linux/amd64
        cache-from:
          - type=registry,ref=registry.robotics-lab.ru/foxglove:cache-arm64
          - type=registry,ref=registry.robotics-lab.ru/foxglove:cache-amd64
        cache-to:
          # - type=registry,ref=registry.robotics-lab.ru/foxglove:cache-arm64
          # - type=registry,ref=registry.robotics-lab.ru/foxglove:cache-amd64
    ports:
      - ${FOXGLOVE_PORT:-8080}:8080
    volumes:
      - foxglove-layouts:/src/layouts

volumes:
  foxglove-layouts:

networks:
  default:
    name: "${CONTAINER_NAME:-foxglove-${USER}}"
